/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface JsDocAddress {
  segmentOrd: number
  docId: number
}
export interface SearchOptions {
  fields?: Array<string>
  limit?: number
}
export interface TopDoc {
  score: number
  docAddress: JsDocAddress
}
export declare function openInDir(pathStr: string): ExternalObject<Index>
export declare function search(index: ExternalObject<Index>, query: string, searchOptions?: SearchOptions | undefined | null): Array<TopDoc>
export declare function getDocumentByAddress(index: ExternalObject<Index>, docAddress: JsDocAddress): string
